services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    depends_on:
      - neo4j
    ports:
      - "8080:8080"
    volumes:
      - '.:/app'

  neo4j:
    image: neo4j:4.4.8-enterprise
    container_name: neo4j
    hostname: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: neo4j/supersecretpassword
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"
      NEO4J_dbms_connector_http_advertised__address: "localhost:7474"
    healthcheck:
      test: [ "CMD-SHELL", "echo RETURN 1 | cypher-shell -a bolt://neo4j:7474 -u neo4j -p supersecretpassword || exit 1" ]
