services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    depends_on:
      - neo4j
    ports:
      - "8080:8080"
    volumes:
      - '.:/app'

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecretpassword
      ME_CONFIG_MONGODB_URL: mongodb://mongo:supersecretpassword@mongo:27017/